#!/usr/bin/env bash

set -o errexit
set -o pipefail

verify_args() {
  if (( $# != 2 )); then
    echo "copy_image_to_pod"
    echo ""
    echo "Usage:"
    echo "  ./copy_image_to_pod <file_path> <pod_name>"
    echo ""
    exit
  fi
}

main() {
  verify_args "$@"
  kubectl cp "$1" "$2":/usr/share/nginx/html/
}

main "$@"
