apiVersion: v1
kind: Service
metadata:
  name: {{ template "my-app.fullname" . }}-deployment
  labels:
    app: {{ template "my-app.name" . }}
    chart: {{ template "my-app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.deployment.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "my-app.name" . }}-deployment
    release: {{ .Release.Name }}
