apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "my-app.fullname" . }}
  labels:
    app: {{ template "my-app.name" . }}
    chart: {{ template "my-app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.statefulSet.replicas }}
  selector:
    matchLabels:
      app: {{ template "my-app.name" . }}-stateful-set
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "my-app.name" . }}-stateful-set
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.statefulSet.image.repository }}:{{ .Values.statefulSet.image.tag }}"
          imagePullPolicy: {{ .Values.statefulSet.image.pullPolicy }}
          command: ["/bin/sh"]
          args: ["-c", "exec nginx -g 'daemon off;'"]
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: "POD"
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: www
              mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
    - metadata:
        name: www
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Mi
