apiVersion: v1
kind: Service
metadata:
  name: {{ template "my-app.fullname" . }}-stateful-set
  labels:
    app: {{ template "my-app.name" . }}
    chart: {{ template "my-app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.statefulSet.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "my-app.name" . }}-stateful-set
    release: {{ .Release.Name }}
